@extends('layouts.app')
@section('title',$country->name)
@section('content')
<div class="container-fluid"><div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div class="d-flex align-items-center gap-3">@if($country->flag)<img src="{{ $country->flag }}" width="72" class="rounded shadow-sm" alt="">@endif<div><h3 class="mb-1">{{ $country->name }}</h3><p class="text-muted mb-0">{{ $country->code }} · {{ $country->region }} · {{ $country->capital }}</p></div></div><div class="d-flex gap-2"><a href="{{ route('countries.index') }}" class="btn btn-outline-secondary"><i class="bi bi-arrow-left"></i></a>@if(auth()->user()->peran === 'admin')<a href="{{ route('countries.edit',$country) }}" class="btn btn-outline-primary"><i class="bi bi-pencil"></i> Edit</a>@else<form method="POST" action="{{ route('watchlist.store',$country) }}">@csrf<button class="btn btn-primary"><i class="bi bi-star"></i> Pantau</button></form>@endif</div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
<div class="row g-3 mb-4">@foreach([['Populasi',number_format($country->population ?? 0),'bi-people','navy'],['Mata Uang',$country->currency_code ?: '-','bi-currency-exchange','accent'],['Bahasa',collect($country->languages)->join(', ') ?: '-','bi-translate','navy'],['Risk Score',$country->riskScore ? number_format($country->riskScore->total_score,2).' '.$country->riskScore->category : 'Belum dihitung','bi-shield','danger'],['Pelabuhan',$country->ports->count(),'bi-geo-alt','success']] as [$label,$value,$icon,$color])<div class="col-sm-6 col-xl"><div class="stat-card h-100"><div class="stat-icon-box stat-icon-{{ $color }}"><i class="bi {{ $icon }}"></i></div><div class="stat-label">{{ $label }}</div><div class="h4 mb-0">{{ $value }}</div></div></div>@endforeach</div>
<div class="row g-4"><div class="col-lg-4"><div class="info-card h-100"><div class="card-header-navy"><i class="bi bi-cloud-sun"></i>Cuaca Open-Meteo</div><div class="card-body">@if($country->weather)<div class="display-5 fw-bold">{{ number_format($country->weather->temperature,1) }}°C</div><p>Angin {{ number_format($country->weather->wind_speed,1) }} km/h<br>Hujan {{ number_format($country->weather->rainfall,1) }} mm<br>Risiko badai {{ number_format($country->weather->storm_risk,1) }}</p><a href="{{ route('weather.show',$country) }}" class="btn btn-outline-primary btn-sm">Detail</a>@else<p class="text-muted">Belum ada data cuaca.</p>@endif @if(auth()->user()->peran==='admin')<a href="{{ route('weather.sync',$country) }}" class="btn btn-primary btn-sm">Sinkronkan</a>@endif</div></div></div>
<div class="col-lg-4"><div class="info-card h-100"><div class="card-header-navy"><i class="bi bi-graph-up"></i>Ekonomi World Bank</div><div class="card-body">@if($country->economicIndicator)<p><strong>GDP:</strong> ${{ number_format($country->economicIndicator->gdp,0) }}<br><strong>Inflasi:</strong> {{ number_format($country->economicIndicator->inflation,2) }}%<br><strong>Pengangguran:</strong> {{ number_format($country->economicIndicator->unemployment,2) }}%<br><strong>Ekspor:</strong> {{ $country->economicIndicator->exports === null ? '-' : '$'.number_format($country->economicIndicator->exports,0) }}<br><strong>Impor:</strong> {{ $country->economicIndicator->imports === null ? '-' : '$'.number_format($country->economicIndicator->imports,0) }}</p><a href="{{ route('economy.show',$country) }}" class="btn btn-outline-primary btn-sm">Detail</a>@else<p class="text-muted">Belum ada indikator ekonomi.</p>@endif @if(auth()->user()->peran==='admin')<a href="{{ route('economy.sync',$country) }}" class="btn btn-primary btn-sm">Sinkronkan</a>@endif</div></div></div>
<div class="col-lg-4"><div class="info-card h-100"><div class="card-header-navy"><i class="bi bi-currency-dollar"></i>Exchange Rate</div><div class="card-body">@if($country->exchangeRate)<div class="h3">{{ number_format($country->exchangeRate->exchange_rate,4) }}</div><p class="text-muted">{{ $country->exchangeRate->base_currency }} / {{ $country->exchangeRate->target_currency }}</p><a href="{{ route('exchange.show',$country) }}" class="btn btn-outline-primary btn-sm">Detail</a>@else<p class="text-muted">Belum ada nilai tukar.</p>@endif @if(auth()->user()->peran==='admin')<a href="{{ route('exchange.sync',$country) }}" class="btn btn-primary btn-sm">Sinkronkan</a>@endif</div></div></div></div>
<div class="info-card mt-4"><div class="card-header-navy"><i class="bi bi-map"></i>Lokasi Negara</div><div class="card-body p-0"><div id="countryMap" style="height:320px"></div></div></div></div>
@endsection
@push('styles')<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">@endpush
@push('scripts')<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>const map=L.map('countryMap').setView([{{ (float)$country->latitude }},{{ (float)$country->longitude }}],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors'}).addTo(map);L.marker([{{ (float)$country->latitude }},{{ (float)$country->longitude }}]).addTo(map).bindPopup(@json($country->name)).openPopup();</script>@endpush
